// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import  'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyUP-fqQbAC0-5-EdZ0G7AUXCUDOFlamU',
    appId: '1:343090900388:android:127182092cc9192840a531',
    messagingSenderId: '343090900388',
    projectId: 'counterapp-6ba03',
    storageBucket: 'counterapp-6ba03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClG0CLYyOITWkMAgZ1mTIKkJxnhb8naSo',
    appId: '1:343090900388:ios:484ece00d3e0ffca40a531',
    messagingSenderId: '343090900388',
    projectId: 'counterapp-6ba03',
    storageBucket: 'counterapp-6ba03.appspot.com',
    iosClientId: '343090900388-9end4t467jhuh0ado51k4bl0g7ekd28m.apps.googleusercontent.com',
    iosBundleId: 'com.saubhagya.app',
  );
}
